# Generated by Django 4.2.7 on 2023-11-25 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10, unique=True)),
                ('no_of_bed', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('ac_non', models.BooleanField()),
                ('room_type', models.CharField(choices=[('dormitory', 'Dormitory')], default='dormitory', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile_no', models.CharField(default='', max_length=15)),
                ('visiting_reason', models.CharField(choices=[('Business', 'Business'), ('Leisure', 'Leisure'), ('Other', 'Other')], default='Other', max_length=20)),
                ('id_proof', models.CharField(choices=[('Aadhar', 'Aadhar Card'), ('Passport', 'Passport'), ('DriverLicense', 'Drivers License'), ('Other', 'Other')], default='Other', max_length=20)),
                ('id_proof_uploaded', models.FileField(upload_to='')),
                ('room_type', models.CharField(default='', max_length=50)),
                ('room_no', models.CharField(default='', max_length=10)),
                ('checkin_date', models.DateField(default=django.utils.timezone.now)),
                ('checkout_date', models.DateField(default=django.utils.timezone.now)),
                ('original_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('notification', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Accept', max_length=10)),
                ('booking_status', models.CharField(choices=[('Request', 'Request'), ('Awaiting', 'Awaiting'), ('Confirm', 'Confirm')], default='Request', max_length=10)),
            ],
        ),
    ]
