# Generated by Django 4.2.4 on 2023-11-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_no", models.CharField(max_length=10, unique=True)),
                ("no_of_bed", models.IntegerField(choices=[(1, "1"), (2, "2")])),
                ("ac_non", models.BooleanField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[("dormitory", "Dormitory")],
                        default="dormitory",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_no", models.CharField(max_length=15)),
                (
                    "visiting_reason",
                    models.CharField(
                        choices=[
                            ("Business", "Business"),
                            ("Leisure", "Leisure"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "id_proof",
                    models.CharField(
                        choices=[
                            ("Aadhar", "Aadhar Card"),
                            ("Passport", "Passport"),
                            ("DriverLicense", "Drivers License"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_proof_uploaded", models.FileField(upload_to="id_proofs/")),
                ("room_type", models.CharField(max_length=50)),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=5)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "notification",
                    models.CharField(
                        choices=[("Accept", "Accept"), ("Reject", "Reject")],
                        max_length=10,
                    ),
                ),
                ("room_no", models.CharField(max_length=10)),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("Request", "Request"),
                            ("Awaiting", "Awaiting"),
                            ("Confirm", "Confirm"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
