# Generated by Django 4.2.4 on 2023-11-21 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("GuestHouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetail",
            name="paid_amount",
        ),
        migrations.AddField(
            model_name="userdetail",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("Request", "Request"),
                    ("Awaiting", "Awaiting"),
                    ("Confirm", "Confirm"),
                ],
                default="Request",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="checkin_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="checkout_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="final_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="id_proof",
            field=models.CharField(
                choices=[
                    ("Aadhar", "Aadhar Card"),
                    ("Passport", "Passport"),
                    ("DriverLicense", "Drivers License"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="id_proof_uploaded",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="mobile_no",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="notification",
            field=models.CharField(
                choices=[("Accept", "Accept"), ("Reject", "Reject")],
                default="Accept",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="room_no",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="room_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="visiting_reason",
            field=models.CharField(
                choices=[
                    ("Business", "Business"),
                    ("Leisure", "Leisure"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
