# Generated by Django 4.2.7 on 2023-12-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicant_no', models.CharField(max_length=10, unique=True)),
                ('program', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=20)),
                ('year_of_admission', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048), (2049, 2049)])),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('phone_no_of_parents', models.CharField(max_length=15)),
                ('email_of_parents', models.EmailField(max_length=254)),
                ('address_of_parents', models.TextField()),
                ('local_guardian_name', models.CharField(max_length=255)),
                ('local_guardian_mobile_no', models.CharField(max_length=15)),
                ('deposit_amount', models.CharField(blank=True, default='Null', max_length=255)),
                ('hostel_name', models.CharField(default='Null', max_length=255)),
                ('user_registered', models.CharField(default='Null', max_length=255)),
                ('room_no', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no', models.CharField(blank=True, max_length=5, null=True)),
                ('total_fees', models.CharField(blank=True, default='Null', max_length=255, null=True)),
                ('fees_paid', models.CharField(blank=True, default='Null', max_length=255, null=True)),
                ('fees_remaining', models.CharField(blank=True, default='Null', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Details',
            fields=[
                ('Hostel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=255)),
                ('hostel_capacity', models.CharField(default='Not Defined', max_length=100)),
                ('hostel_warden_1', models.CharField(max_length=100)),
                ('hostel_warden_2', models.CharField(max_length=100, null=True)),
                ('hostel_address', models.TextField()),
                ('mess_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('mess_fees', models.CharField(blank=True, max_length=255, null=True)),
                ('hostel_image', models.ImageField(default='image not available', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('no_of_beds', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=255)),
                ('bed_no1_id', models.CharField(max_length=10)),
                ('bed_no1_price', models.CharField(default='5000', max_length=255)),
                ('bed_no2_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no2_price', models.CharField(blank=True, max_length=255, null=True)),
                ('bed_no3_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no3_price', models.CharField(blank=True, max_length=255, null=True)),
                ('bed_no4_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no4_price', models.CharField(blank=True, max_length=255, null=True)),
                ('bathroom_attached', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FeesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Admin_incharge', models.CharField(default='Admin', max_length=50)),
                ('installment', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=50)),
                ('include_food', models.BooleanField()),
                ('final_amount', models.CharField(blank=True, default='Null', max_length=255)),
                ('transaction_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking'), ('Debit_Card', 'Debit_Card'), ('Credit_Card', 'Credit_Card'), ('Paytm', 'Paytm'), ('PhonePay', 'PhonePay'), ('GooglePay', 'GooglePay')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.applicant_details')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=50, null=True)),
                ('usertype', models.CharField(choices=[('Super_admin', 'Super_admin'), ('Hostel_admin', 'Hostel_admin'), ('Guest_admin', 'Guest_admin'), ('User', 'User')], default='User', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Assigned', 'Assigned')], default='Active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
