# Generated by Django 4.2.7 on 2023-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('applicant_no', models.CharField(max_length=10, unique=True)),
                ('program', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('year_of_admission', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)])),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('phone_no_of_parents', models.CharField(max_length=15)),
                ('email_of_parents', models.EmailField(max_length=254)),
                ('address_of_parents', models.TextField()),
                ('local_guardian_name', models.CharField(max_length=255)),
                ('local_guardian_mobile_no', models.CharField(max_length=15)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=5)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel_Details',
            fields=[
                ('Hostel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=255)),
                ('hostel_warden', models.CharField(max_length=100)),
                ('hostel_address', models.TextField()),
                ('mess_vendor', models.CharField(max_length=255)),
                ('mess_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('no_of_beds', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('bed_no1_id', models.CharField(max_length=10)),
                ('bed_no1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed_no2_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bed_no3_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bed_no4_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no4_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bathroom_attached', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
