# Generated by Django 3.0.5 on 2023-11-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel_Details',
            fields=[
                ('Hostel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=255)),
                ('hostel_warden', models.CharField(max_length=100)),
                ('hostel_address', models.TextField()),
                ('mess_vendor', models.CharField(max_length=255)),
                ('mess_fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('no_of_beds', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('bed_no1_id', models.CharField(max_length=10)),
                ('bed_no1_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bed_no2_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bed_no3_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bed_no4_id', models.CharField(blank=True, max_length=10, null=True)),
                ('bed_no4_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bathroom_attached', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
    ]
