# Generated by Django 4.2.7 on 2023-11-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_details',
            name='mess_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostel_details',
            name='mess_vendor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
