# Generated by Django 4.2.4 on 2023-12-01 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0002_alter_hostel_details_hostel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestroom_Details',
            fields=[
                ('Guestroom_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Guestroom_name', models.CharField(max_length=255)),
                ('Guestroom_capacity', models.CharField(default='Not Defined', max_length=100)),
                ('Guestroom_admin_1', models.CharField(max_length=100)),
                ('Guestroom_admin_2', models.CharField(max_length=100, null=True)),
                ('Guestroom_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuestRoomcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guestroom_name', models.CharField(default='null', max_length=255)),
                ('Guestroom_bed_count', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('Guestroom_room_number', models.CharField(max_length=10, unique=True)),
                ('Guestroom_room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Dormetry', 'Dormetry'), ('AC_Single', 'AC_Single'), ('AC_Double', 'AC_Double')], default='single', max_length=20)),
                ('Guestroom_with_AC', models.BooleanField(default=False)),
                ('Guestroom_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Guestroom_is_booked', models.BooleanField(choices=[(True, 'Booked'), (False, 'Vacant')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guestroomuserdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address_proof', models.FileField(upload_to='')),
                ('reason_of_visiting', models.CharField(default='Other', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_of_checkin', models.DateField(default=django.utils.timezone.now)),
                ('date_of_checkout', models.DateField(default=django.utils.timezone.now)),
                ('room_type', models.CharField(max_length=50)),
                ('final_amount', models.CharField(max_length=10)),
                ('discount', models.CharField(default=0, max_length=5)),
                ('paid_amount', models.CharField(default=0, max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('booking_status', models.CharField(choices=[('Request', 'Request'), ('Awaiting', 'Awaiting'), ('Confirm', 'Confirm')], default='Request', max_length=10)),
                ('notification', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Accept', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='feestransaction',
            name='total_fees',
        ),
        migrations.AddField(
            model_name='applicant_details',
            name='user_registered',
            field=models.CharField(default='Null', max_length=255),
        ),
        migrations.AddField(
            model_name='feestransaction',
            name='Admin_incharge',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='bed_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='deposit_amount',
            field=models.CharField(blank=True, default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='fees_paid',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='fees_remaining',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='program',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='total_fees',
            field=models.CharField(blank=True, default='Null', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feestransaction',
            name='final_amount',
            field=models.CharField(blank=True, default='Null', max_length=255),
        ),
        migrations.AlterField(
            model_name='feestransaction',
            name='transaction_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking'), ('Debit_Card', 'Debit_Card'), ('Credit_Card', 'Credit_Card'), ('Paytm', 'Paytm'), ('PhonePay', 'PhonePay'), ('GooglePay', 'GooglePay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='hostel_details',
            name='mess_fees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no1_price',
            field=models.CharField(default='5000', max_length=255),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no2_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no3_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no4_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='no_of_beds',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=255),
        ),
    ]
