# Generated by Django 4.2.4 on 2023-11-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_applicant_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('include_food', models.BooleanField()),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('NetBanking', 'NetBanking'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Paytm', 'Paytm'), ('PhonePay', 'PhonePay'), ('GooglePay', 'GooglePay')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.applicant_details')),
            ],
        ),
    ]
