# Generated by Django 4.2.4 on 2023-12-01 21:18

import Hostel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_guestroom_details_guestroomcreation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroomuserdetails',
            name='address_proof',
            field=models.FileField(blank=True, upload_to='proofimage/', validators=[Hostel.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='guestroomuserdetails',
            name='date_of_birth',
            field=models.DateField(default='null', null=True),
        ),
    ]
