# Generated by Django 4.2.4 on 2023-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(choices=[('Super_admin', 'Super_admin'), ('Hostel_admin', 'Hostel_admin'), ('Guest_admin', 'Guest_admin'), ('User', 'User')], default='User', max_length=20),
        ),
    ]
