# Generated by Django 4.2.4 on 2023-11-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0003_applicant_details_user_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_details',
            name='deposit_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='fees_paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='fees_remaining',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='program',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant_details',
            name='total_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feestransaction',
            name='final_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='feestransaction',
            name='total_fees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostel_details',
            name='mess_fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no1_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no2_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no3_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostelroomdetails',
            name='bed_no4_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
