# Generated by Django 4.2.4 on 2023-12-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_alter_guestroomuserdetails_address_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroomuserdetails',
            name='date_of_birth',
            field=models.DateField(default=None, null=True),
        ),
    ]
