# Generated by Django 4.2.4 on 2023-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_remove_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel_details',
            name='hostel_capacity',
        ),
        migrations.RemoveField(
            model_name='hostel_details',
            name='hostel_type',
        ),
        migrations.AddField(
            model_name='hostel_details',
            name='hostel_image',
            field=models.ImageField(default='image not available', upload_to=''),
        ),
    ]
