# Generated by Django 4.2.4 on 2023-12-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_alter_guestroomuserdetails_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestroomuserdetails',
            name='date_of_checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guestroomuserdetails',
            name='date_of_checkout',
            field=models.DateField(),
        ),
    ]
