# Generated by Django 4.2.4 on 2023-12-01 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_remove_feestransaction_total_fees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoomcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Dormetry', 'Dormetry'), ('AC_Single', 'AC_Single'), ('AC_Double', 'AC_Double')], default='single', max_length=20)),
                ('bed_count', models.PositiveIntegerField()),
                ('has_AC', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_booked', models.BooleanField(choices=[(True, 'Booked'), (False, 'Vacant')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guestroomuserdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address_proof', models.FileField(upload_to='')),
                ('reason_of_visiting', models.CharField(default='Other', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_of_checkin', models.DateField(default=django.utils.timezone.now)),
                ('date_of_checkout', models.DateField(default=django.utils.timezone.now)),
                ('room_type', models.CharField(max_length=50)),
                ('final_amount', models.CharField(max_length=10)),
                ('discount', models.CharField(default=0, max_length=5)),
                ('paid_amount', models.CharField(default=0, max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('booking_status', models.CharField(choices=[('Request', 'Request'), ('Awaiting', 'Awaiting'), ('Confirm', 'Confirm')], default='Request', max_length=10)),
                ('notification', models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], default='Accept', max_length=10)),
            ],
        ),
    ]
