# Generated by Django 3.2.4 on 2023-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_remove_feestransaction_total_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_details',
            name='hostel_warden_1',
            field=models.CharField(max_length=255),
        ),
    ]
