# Generated by Django 4.2.4 on 2023-11-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0005_applicant_details_hostel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestransaction',
            name='installment',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Half Yearly', 'Half Yearly'), ('Yearly', 'Yearly')], max_length=50),
        ),
    ]
