# Generated by Django 4.2.4 on 2023-12-02 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_alter_guestroomuserdetails_date_of_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_visiting', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hostel.customuser')),
            ],
        ),
    ]
