# Generated by Django 4.2.4 on 2023-12-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_guestroomcreation_guestroomuserdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestroom_Details',
            fields=[
                ('Guestroom_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Guestroom_name', models.CharField(max_length=255)),
                ('Guestroom_capacity', models.CharField(default='Not Defined', max_length=100)),
                ('Guestroom_admin_1', models.CharField(max_length=100)),
                ('Guestroom_admin_2', models.CharField(max_length=100, null=True)),
                ('Guestroom_address', models.TextField()),
            ],
        ),
    ]
