# Generated by Django 4.2.4 on 2023-11-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_alter_feestransaction_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('usertype', models.CharField(choices=[('Super_admin', 'Super Admin'), ('Hostel_Admin', 'Hostel Admin'), ('Guest_Admin', 'Guest Admin'), ('User', 'User')], default='User', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Assigned', 'Assigned')], default='Active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='hostel_details',
            name='hostel_capacity',
            field=models.CharField(default='Not Defined', max_length=100),
        ),
        migrations.AddField(
            model_name='hostel_details',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], default='Others', max_length=50),
        ),
    ]
