# Generated by Django 3.2.4 on 2023-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0006_alter_hostel_details_hostel_warden_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel_details',
            name='hostel_warden_1',
            field=models.CharField(max_length=100),
        ),
    ]
