# Generated by Django 4.2.4 on 2023-12-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
