# Generated by Django 4.2.4 on 2023-11-14 10:21

import Hostel.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0008_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Hostel.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
