# Generated by Django 4.2.4 on 2023-12-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0008_guestroomcreation_guestroom_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='bed_count',
            new_name='Guestroom_bed_count',
        ),
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='is_booked',
            new_name='Guestroom_is_booked',
        ),
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='price',
            new_name='Guestroom_price',
        ),
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='room_number',
            new_name='Guestroom_room_number',
        ),
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='room_type',
            new_name='Guestroom_room_type',
        ),
        migrations.RenameField(
            model_name='guestroomcreation',
            old_name='has_AC',
            new_name='Guestroom_with_AC',
        ),
    ]
